version: '3.5'

services:
    app:
        image: node:14
        volumes: 
            - .:/app:cached
        working_dir: /app
        ports:
            - 3000:3000
        # command: npm start
        command: npm start
